require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '11.0'

target 'openvidu_react_native' do
  # Pods for openvidu_react_native
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

#  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
#  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
#  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"
#  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
#  pod 'React-Core', :path => '../node_modules/react-native/'
#  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'ReactCommon/callinvoker', :path => '../node_modules/react-native/ReactCommon'
#  pod 'ReactCommon/turbomodule/core', :path => '../node_modules/react-native/ReactCommon'
#  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true
#
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  target 'openvidu_react_nativeTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'openvidu_react_native-tvOS' do
  # Pods for openvidu_react_native-tvOS

  target 'openvidu_react_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
