require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

install! 'cocoapods', :deterministic_uuids => false

platform :ios, '13.0'

target 'openvidu_react_native' do
  # Pods for openvidu_react_native
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'react-native-webrtc', :path => '../node_modules/react-native-webrtc'

  target 'openvidu_react_nativeTests' do
    inherit! :complete
    # Pods for testing
  end
end

target 'openvidu_react_native-tvOS' do
  # Pods for openvidu_react_native-tvOS

  target 'openvidu_react_native-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
